# modules/report_generator.py
"""
Report generation utilities for MERIT platform
"""

from typing import Dict, List
from datetime import datetime
import json

class ReportGenerator:
    """Generate various report formats from review results"""
    
    @staticmethod
    def generate_html_report(methodology_results: Dict, 
                            statistics_results: Dict, 
                            results_results: Dict,
                            editorial_decision: Dict) -> str:
        """Generate an HTML formatted report"""
        
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>MERIT Editorial Review Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
                .header {{ background: #2c3e50; color: white; padding: 20px; text-align: center; }}
                .score-card {{ background: #ecf0f1; padding: 15px; margin: 10px 0; border-radius: 5px; }}
                .critical {{ background: #e74c3c20; border-left: 4px solid #e74c3c; padding: 10px; margin: 10px 0; }}
                .strength {{ background: #2ecc7120; border-left: 4px solid #2ecc71; padding: 10px; margin: 10px 0; }}
                .decision {{ background: #3498db20; border-left: 4px solid #3498db; padding: 15px; margin: 20px 0; }}
                table {{ width: 100%; border-collapse: collapse; }}
                th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
                th {{ background: #34495e; color: white; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>MERIT Editorial Review Report</h1>
                <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>
            
            <div class="decision">
                <h2>Editorial Decision: {editorial_decision.get('decision', 'Pending')}</h2>
                <p>{editorial_decision.get('justification', '')}</p>
                <p><strong>Confidence:</strong> {editorial_decision.get('confidence', 0):.0%}</p>
            </div>
            
            <h2>Quality Scores</h2>
            <table>
                <tr><th>Section</th><th>Score</th></tr>
                <tr><td>Methodology</td><td>{methodology_results.get('overall_score', 0):.1%}</td></tr>
                <tr><td>Statistics</td><td>{statistics_results.get('overall_score', 0):.1%}</td></tr>
                <tr><td>Results Reporting</td><td>{results_results.get('overall_score', 0):.1%}</td></tr>
            </table>
        </body>
        </html>
        """
        return html
    
    @staticmethod
    def generate_markdown_report(methodology_results: Dict,
                                 statistics_results: Dict,
                                 results_results: Dict,
                                 editorial_decision: Dict) -> str:
        """Generate a Markdown formatted report"""
        
        md = f"""# MERIT Editorial Review Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Editorial Decision

**Decision:** {editorial_decision.get('decision', 'Pending')}

**Justification:** {editorial_decision.get('justification', '')}

**Confidence:** {editorial_decision.get('confidence', 0):.0%}

## Quality Scores

| Section | Score |
|---------|-------|
| Methodology | {methodology_results.get('overall_score', 0):.1%} |
| Statistics | {statistics_results.get('overall_score', 0):.1%} |
| Results Reporting | {results_results.get('overall_score', 0):.1%} |

---
*Report generated by MERIT - Manuscript Editorial Review & Intelligence Tool*
"""
        return md